### ISSUE TITLE
Doesnot work on iOS 18.2

### ISSUE THREAD

**Issue by Arslan007** [exendahal/maui_wifi_manager#30]
I have tried the demo app on iOS physical device. Doesnot work as i am getting no network info. Cannot connect to wifi as well.
Tried on latest iOS 18.2 and confirm all permissions were granted and provisioning profile have all the permission entitlements that are required

**Comment by exendahal** [comment]
What is the target version for your application? Is this issue specific to iOS 18.2, or are you experiencing it on other versions as well? I previously tested on iOS 18.1 and encountered no issues with connecting or retrieving network information.

**Comment by Arslan007** [comment]
I have two physical devices and both are on iOS 18.2 and I tried on that and I used the sample app that you have. 
My development provisioning profile have all the required persmissions for WIFI but do you think if I am missing anything else ?

**Comment by Arslan007** [comment]
Also somehow i cannot install demo app when entitlements.plist exist. And when I delete it works

**Comment by exendahal** [comment]
`entitlements.plist` is required in order to app work correctly. 
Pre-requisites as listed [here](https://stackoverflow.com/questions/64676100/how-to-get-ssid-of-currently-connected-wifi-network-in-swift-ios-14)
- You must have a paid developer account
- You must have a physical Device
- You must enable Wifi-Entitlement by going to Target->Signing & Capabilities and adding Access WiFi Information or adding <key>com.apple.developer.networking.wifi-info</key> <true/> directly to your entitlements file
- Allow location usage access from user
